--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------
drop table item;

  CREATE TABLE "C##LEVELUP"."ITEM" 
   (	"ITEM_ID" NUMBER, 
	"ITEM_TYPE" VARCHAR2(256 BYTE), 
	"ITEM_DATA" VARCHAR2(4000 BYTE), 
	"ITEM_NAME" VARCHAR2(256 BYTE), 
	"PRICE" NUMBER, 
	"GAMEPRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##LEVELUP"."ITEM"."ITEM_ID" IS '아이템 ID';
   COMMENT ON COLUMN "C##LEVELUP"."ITEM"."ITEM_TYPE" IS '아이템종류';
   COMMENT ON COLUMN "C##LEVELUP"."ITEM"."ITEM_DATA" IS '아이템데이터';
   COMMENT ON TABLE "C##LEVELUP"."ITEM"  IS '아이템';
REM INSERTING into C##LEVELUP.ITEM
SET DEFINE OFF;
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (608,'HEALING',null,'Fertility Potion',2500,25000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (613,'HEALING',null,'Purification Potion',2500,25000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (614,'HEALING',null,'Sailor''s Stew',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (615,'HEALING',null,'Treasure Map',4500,45000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (625,'USABLE',null,'Seafood Plate',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (626,'USABLE',null,'Barbecue Plate',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (627,'USABLE',null,'Veggie Plate',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1000,'ARMOR',null,'Copper Necklace',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1001,'ARMOR',null,'Silver Necklace',2000,20000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1002,'ARMOR',null,'Gold Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1003,'ARMOR',null,'Platinum Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1004,'ARMOR',null,'Copper Four-Leaf Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1005,'ARMOR',null,'Silver Four-Leaf Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1006,'ARMOR',null,'Golden Four-Leaf Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1007,'ARMOR',null,'Platinum Four-Leaf Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1008,'ARMOR',null,'Tooth Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1009,'ARMOR',null,'Teeth Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1010,'ARMOR',null,'Barbarian Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1011,'ARMOR',null,'Heart Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1012,'ARMOR',null,'Mouboo Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1013,'ARMOR',null,'Skull Necklace',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1100,'ARMOR',null,'Simple Copper Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1101,'ARMOR',null,'Simple Silver Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1102,'ARMOR',null,'Simple Golden Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1103,'ARMOR',null,'Simple Platinum Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1104,'ARMOR',null,'Soul Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1105,'ARMOR',null,'Copper Ring',1000,10000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1106,'ARMOR',null,'Silver Ring',2000,20000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1107,'ARMOR',null,'Gold Ring',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1108,'ARMOR',null,'Platinum Ring',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1109,'ARMOR',null,'Copper Signet Ring',5000,50000);
Insert into C##LEVELUP.ITEM (ITEM_ID,ITEM_TYPE,ITEM_DATA,ITEM_NAME,PRICE,GAMEPRICE) values (1110,'ARMOR',null,'Silver Signet Ring',5000,50000);
--------------------------------------------------------
--  DDL for Index PK_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEVELUP"."PK_ITEM" ON "C##LEVELUP"."ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "C##LEVELUP"."ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##LEVELUP"."ITEM" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##LEVELUP"."ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEVELUP"."ITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##LEVELUP"."ITEM" MODIFY ("GAMEPRICE" NOT NULL ENABLE);
