
INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user2', '2', '문의 제목 2', '문의 내용 2', 'N', sysdate, null, null, null, 'B');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user3', '3', '문의 제목 3', '문의 내용 3', 'N', sysdate, null, null, null, 'C');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user4', '4', '문의 제목 4', '문의 내용 4', 'N', sysdate, null, null, null, 'D');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user5', '5', '문의 제목 5', '문의 내용 5', 'N', sysdate, null, null, null, 'E');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user6', '6', '문의 제목 6', '문의 내용 6', 'N', sysdate, null, null, null, 'F');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user7', '7', '문의 제목 7', '문의 내용 7', 'N', sysdate, null, null, null, 'G');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user8', '8', '문의 제목 8', '문의 내용 8', 'N', sysdate, null, null, null, 'H');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user9', '9', '문의 제목 9', '문의 내용 9', 'N', sysdate, null, null, null, 'I');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user10', '10', '문의 제목 10', '문의 내용 10', 'N', sysdate, null, null, null, 'J');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user11', '11', '문의 제목 11', '문의 내용 11', 'N', sysdate, null, null, null, 'K');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user12', '12', '문의 제목 12', '문의 내용 12', 'N', sysdate, null, null, null, 'L');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user13', '13', '문의 제목 13', '문의 내용 13', 'N', sysdate, null, null, null, 'M');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user14', '14', '문의 제목 14', '문의 내용 14', 'N', sysdate, null, null, null, 'N');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user15', '15', '문의 제목 15', '문의 내용 15', 'N', sysdate, null, null, null, 'O');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user16', '16', '문의 제목 16', '문의 내용 16', 'N', sysdate, null, null, null, 'P');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user17', '17', '문의 제목 17', '문의 내용 17', 'N', sysdate, null, null, null, 'Q');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user18', '18', '문의 제목 18', '문의 내용 18', 'N', sysdate, null, null, null, 'R');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user19', '19', '문의 제목 19', '문의 내용 19', 'N', sysdate, null, null, null, 'S');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user20', '20', '문의 제목 20', '문의 내용 20', 'N', sysdate, null, null, null, 'T');

INSERT INTO INQUIRY (INQUIRY_ID, USERID, EMPLOYEE_ID, INQUIRY_TITLE, INQUIRY_CONTENT, ANSWER_STATUS, EDIT_DATE, ANSWER_DATE, ANSWER_CONTENT, ATTACHEMENT_FILENAME, INQUIRY_TYPE)
VALUES (sys_guid(), 'user21', '21', '문의 제목 21', '문의 내용 21', 'N', sysdate, null, null, null, 'U');
commit;



