---------------------------- 아이템 변경/삭제/환불 기안 MANAGER_ID(승인자), ITEM_NAME(기존아이템 이름), ITEM_AMOUNT (기존아이템 수량) 추가
ALTER TABLE CASE_ITEM_CHANGE
ADD MANAGER_ID RAW(16);

ALTER TABLE CASE_ITEM_DELETE
ADD MANAGER_ID RAW(16);

ALTER TABLE CASE_ITEM_REFUND
ADD MANAGER_ID RAW(16);

ALTER TABLE CASE_ITEM_CHANGE
ADD (ITEM_NAME VARCHAR2(300), ITEM_AMOUNT NUMBER);

ALTER TABLE CASE_ITEM_DELETE
ADD (ITEM_NAME VARCHAR2(300), ITEM_AMOUNT NUMBER);

ALTER TABLE CASE_ITEM_REFUND
ADD (ITEM_NAME VARCHAR2(300), ITEM_AMOUNT NUMBER);
---------------------------- 아이템 변경기안 NOT NULL CONTRAINT 추가
ALTER TABLE CASE_ITEM_CHANGE
MODIFY MANAGER_ID NOT NULL;

ALTER TABLE CASE_ITEM_CHANGE
MODIFY ITEM_NAME NOT NULL;

ALTER TABLE CASE_ITEM_CHANGE
MODIFY ITEM_AMOUNT NOT NULL;
---------------------------- 아이템 삭제기안 NOT NULL CONTRAINT 추가
ALTER TABLE CASE_ITEM_DELETE
MODIFY MANAGER_ID NOT NULL;

ALTER TABLE CASE_ITEM_DELETE
MODIFY ITEM_NAME NOT NULL;

ALTER TABLE CASE_ITEM_DELETE
MODIFY ITEM_AMOUNT NOT NULL;
---------------------------- 아이템 환불기안 NOT NULL CONTRAINT 추가
ALTER TABLE CASE_ITEM_REFUND
MODIFY MANAGER_ID NOT NULL;

ALTER TABLE CASE_ITEM_REFUND
MODIFY ITEM_NAME NOT NULL;

ALTER TABLE CASE_ITEM_REFUND
MODIFY ITEM_AMOUNT NOT NULL;
--------------------------- 아이템 변경 기안 컬럼명 변경
ALTER TABLE CASE_ITEM_CHANGE
RENAME COLUMN REPLACE_ITEM_NO TO REPLACE_ITEM_AMOUNT;

