INSERT INTO DEPARTMENT
VALUES('dev', '개발부');

INSERT INTO DEPARTMENT
VALUES('marketing', '영업부');

INSERT INTO DEPARTMENT
VALUES('trade', '무역부');


INSERT INTO DEPARTMENT
VALUES('accounting', '경리부');


INSERT INTO DEPARTMENT
VALUES('none', '미정');

COMMIT;