--------------------------------------------------------
--  파일이 생성됨 - 월요일-10월-23-2023   
--------------------------------------------------------
DROP TABLE "COMMUNITY" cascade constraints;
--------------------------------------------------------
--  DDL for Table COMMUNITY
--------------------------------------------------------

  CREATE TABLE "COMMUNITY" 
   (	"BOARD_ID" RAW(16) DEFAULT sys_guid(), 
	"DEPARTMENT_ID" VARCHAR2(32), 
	"EMPLOYEE_ID" RAW(16) DEFAULT sys_guid(), 
	"BOARD_TITLE" VARCHAR2(4000), 
	"BOARD_DATE" DATE DEFAULT sysdate, 
	"ATTACHEMENT_FILENAME" VARCHAR2(1000), 
	"BOARD_TYPE" VARCHAR2(1) DEFAULT 'b', 
	"READ_COUNT" NUMBER, 
	"REF_ID" RAW(16), 
	"BOARD_BODY" CLOB, 
	"TEAM_ID" VARCHAR2(32), 
	"REFYN" VARCHAR2(1) DEFAULT 'n', 
	"DELYN" VARCHAR2(1) DEFAULT 'n'
   ) 

   COMMENT ON COLUMN "COMMUNITY"."BOARD_ID" IS '게시글 ID'
   COMMENT ON COLUMN "COMMUNITY"."DEPARTMENT_ID" IS '부서 ID'
   COMMENT ON COLUMN "COMMUNITY"."EMPLOYEE_ID" IS '작성자 ID'
   COMMENT ON COLUMN "COMMUNITY"."BOARD_TITLE" IS '제목'
   COMMENT ON COLUMN "COMMUNITY"."BOARD_DATE" IS '날짜'
   COMMENT ON COLUMN "COMMUNITY"."ATTACHEMENT_FILENAME" IS '첨부파일'
   COMMENT ON COLUMN "COMMUNITY"."BOARD_TYPE" IS '게시판 분류'
   COMMENT ON COLUMN "COMMUNITY"."READ_COUNT" IS '조회수'
   COMMENT ON COLUMN "COMMUNITY"."REF_ID" IS '원글 레퍼런스'
   COMMENT ON COLUMN "COMMUNITY"."BOARD_BODY" IS '본문(clob)'
   COMMENT ON TABLE "COMMUNITY"  IS '게시글'
REM INSERTING into COMMUNITY
SET DEFINE OFF;
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('EB168D44A607491FAFC0A04DD71A1BB4','dev','E37B3B8A4FF54582A91A8DDBD0D64665','파일 안올리기 테스트',to_date('23/10/23','RR/MM/DD'),'(null)','b',0,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('C06114309DD94D7D8245EBC8AE6A3F7B','dev','E37B3B8A4FF54582A91A8DDBD0D64665','1111',to_date('23/10/23','RR/MM/DD'),null,'b',0,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('706EF8AFA18A4DAEB38BB3BA5F9484EA','dev','E37B3B8A4FF54582A91A8DDBD0D64665','Awesome title',to_date('23/10/21','RR/MM/DD'),null,'b',9,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('A1C9F61389A743AE8FC76D6827FCF495','dev','E37B3B8A4FF54582A91A8DDBD0D64665','1111',to_date('23/10/22','RR/MM/DD'),'(null)','b',2,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('A858664A878D4A1B96A455D6EC400FE5','dev','E37B3B8A4FF54582A91A8DDBD0D64665','글 쓰기 테스트1',to_date('23/10/22','RR/MM/DD'),'(null)','b',2,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('7DECF25C274F4DB1BA9930CB9E231FB5','dev','E37B3B8A4FF54582A91A8DDBD0D64665','새로운 글',to_date('23/10/22','RR/MM/DD'),'["20230802_091556.jpg"]','b',12,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('DC4029491675412A86DAADB847B8D4E8','dev','E37B3B8A4FF54582A91A8DDBD0D64665','딱 10분',to_date('23/10/23','RR/MM/DD'),'(null)','b',0,null,'backend','n','n');
Insert into COMMUNITY (BOARD_ID,DEPARTMENT_ID,EMPLOYEE_ID,BOARD_TITLE,BOARD_DATE,ATTACHEMENT_FILENAME,BOARD_TYPE,READ_COUNT,REF_ID,TEAM_ID,REFYN,DELYN) values ('575C01ABCC87495D9A75E627E9EB1C20','dev','E37B3B8A4FF54582A91A8DDBD0D64665','파일 안올리기 테스트',to_date('23/10/23','RR/MM/DD'),null,'b',0,null,'backend','n','n');
--------------------------------------------------------
--  DDL for Index PK_COMMUNITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COMMUNITY" ON "COMMUNITY" ("BOARD_ID")
--------------------------------------------------------
--  Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "COMMUNITY" MODIFY ("BOARD_ID" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("BOARD_TITLE" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("BOARD_DATE" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("BOARD_TYPE" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("READ_COUNT" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" ADD CONSTRAINT "PK_COMMUNITY" PRIMARY KEY ("BOARD_ID")
  USING INDEX  ENABLE
  ALTER TABLE "COMMUNITY" MODIFY ("REFYN" NOT NULL ENABLE)
  ALTER TABLE "COMMUNITY" MODIFY ("DELYN" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_EMPLOYEE_TO_COMMUNITY" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEE_ID") ENABLE
  ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_DEPARTMENT_TO_COMMUNITY" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENT_ID") ENABLE
  ALTER TABLE "COMMUNITY" ADD FOREIGN KEY ("REF_ID")
	  REFERENCES "COMMUNITY" ("BOARD_ID") ENABLE
  ALTER TABLE "COMMUNITY" ADD FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TEAM" ("TEAM_ID") ENABLE
